name: Update Schweiger Job Feed

on:
  schedule:
    # Runs every day at 8:00 PM CST (CST = UTC-6)
    - cron: "0 2 * * *"
  workflow_dispatch:  # allows manual trigger in GitHub UI

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas webdriver-manager

      - name: Install Firefox and Geckodriver (headless compatible)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget libgtk-3-0 libdbus-glib-1-2 libxt6 libx11-xcb1 libasound2
          # Install Firefox directly from Mozilla (not Snap)
          FIREFOX_VERSION=$(curl -s https://product-details.mozilla.org/1.0/firefox_versions.json | grep -oP '"LATEST_FIREFOX_VERSION":\s*"\K[^"]+')
          wget -O firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-${FIREFOX_VERSION}-linux64&lang=en-US"
          tar -xjf firefox.tar.bz2
          sudo mv firefox /opt/firefox
          sudo ln -s /opt/firefox/firefox /usr/local/bin/firefox
          # Install latest Geckodriver
          GECKO_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep "tag_name" | cut -d '"' -f 4)
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKO_VERSION/geckodriver-$GECKO_VERSION-linux64.tar.gz
          tar -xvzf geckodriver-$GECKO_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Verify Firefox installation
        run: |
          firefox --version
          geckodriver --version

      - name: Run job scraper
        run: |
          python jobboardscraper.py

      - name: Generate XML feed
        run: |
          python generate_xml_feed.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update XML feed" || echo "No changes to commit"
          git push
