name: Update Schweiger Job Feed

on:
  schedule:
    # Runs every day at 8:00 PM CST (CST = UTC-6)
    - cron: "0 2 * * *"
  workflow_dispatch:  # allows manual trigger in GitHub UI

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install selenium pandas webdriver-manager

      - name: Run job scraper
        run: |
          python jobboardscraper.py

      - name: Generate XML feed
        run: |
          python generate_xml_feed.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update XML feed" || echo "No changes to commit"
          git push
