name: Update Schweiger Job Feed

on:
  schedule:
    - cron: "0 2 * * *"  # 8:00 PM CST daily
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable || true

      - name: Install Python dependencies
        run: |
          pip install selenium pandas webdriver-manager lxml bs4

      - name: Run job scraper
        run: |
          python jobboardscraper.py

      - name: Generate cleaned XML
        run: |
          python generate_xml_feed.py

      - name: Move XML for Pages
        run: |
          mv schweiger_jobs.xml schweiger_jobs.xml

      - name: Commit and force push updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add schweiger_jobs.xml
          git commit -m "Auto-update XML feed" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push -f origin main
